schoolsystem/Event/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cal'

urlpatterns = [  
    path("register/",views.register_event,name="register_event"),
    path('cal/', views.CalendarView.as_view(), name='calendar'),
    url('list/', views.event, name='event_new'),
	url('edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),  
]

schoolsystem/api/urls.py
from  django.urls import path,include
from  rest_framework import routers
from.views import CourseViewset, EventViewset, StudentViewset, TrainerViewset

router=routers.DefaultRouter()
router.register("students/",StudentViewset)
router.register("trainers/", TrainerViewset)
router.register("courses/",CourseViewset)
router.register("events/",EventViewset)

urlpatterns=[
      path("",include(router.urls)),

]

schoolsystem/core/urls.py
from django.conf.urls import url
from django.urls import path
from .views import home

urlpatterns =[
    path("", home ,name="home_views"),
    
]

schoolsystem/schoolsystem/urls.py
from django.conf import settings
from django.conf.urls.static import static

"""schoolsystem URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.conf.urls import include
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/',include("student.urls")),
    path('Trainer/',include("Trainer.urls")),
    path('Course/',include("Course.urls")),
    path('Event/', include("Event.urls")),
    path("",include("core.urls")),
    path('api/',include("api.urls")),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns+=staticfiles_urlpatterns()

schoolsystem/core/models.py
from django.db import models

# Create your models here.

schoolsystem/core/views.py
from django.shortcuts import render
from student.models import Student
from Course.models import Course
from Trainer.models import Trainer
from Event.models import Event






# Create your views here.
def home(request):
    students=Student.objects.count()
    trainers=Trainer.objects.count()
    courses= Course.objects.count()
    events=Event.objects.count()
    data={"students":students,"trainers":trainers, "courses":courses ,"events":events}
    return render(request,"homepage.html",data)
    

schoolsystem/core/templates/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}AkiraChix Site{% endblock %}</title>
</head>

<body>
	<style >
		body{
      background:   url("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAKo6-7eFpJ_EShuhhGK-bqCC2cdf35W7QMA&usqp=CAU") no-repeat center;

			background-size: cover;
		}
		.sidenav {
			height:100%;
			width:160px;
			position: fixed;
			z-index:1;
			top:0;
			left:0;
			background-color:rgb(153, 56, 153);
			position: fixed;
			overflow-x:hidden;
			padding-top:20px;
		}
 
		.sidenav a {
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size:25px;
			color: #0a0a0a;
			display:block;
		}
 
		.sidenav a:hover{
			color:#f1f1f1;
		}	
 
		.main{
			margin-left:160px;
			padding: 0px 10px;
		}
        h1{
            text-align: center;
        }
        .pic{
			background-size: cover;
	
		}
		img{
			background-size: cover;
			height: 600px;
			width: 700px;
		
		}
    .logo{
      height: 20px;
      width: 20px;
    }
    .home{
    display: flex;
  
    background-blend-mode: screen;
    height: 50vh;
    color: rgb(12, 72, 150);
    min-height: 500px;
    opacity: 90%;
    background-size: 65%;
    background-attachment: fixed;
    font-family: 'Roboto Slab', serif; 
}
.home .max-width{
  width: 100%;
 
  justify-content: center;
  align-items: center;
}
.home .max-width .row{
  margin-right: 6px;
  margin-top: 30%;
}

.home .home-content .text-2{
 
    font-size: 40px;
    font-weight: 600;
    margin-right: -3px;
    text-align: center;
    padding-bottom: -70px;
}
.home-content{
    text-align: center;
}

.student{
             
             background: none;
             width: 20%;  
             
              font-size: 18px;  
              font-weight: bolder;
              padding: 10px; 
             
              margin: 20px 0px;   
              border: solid 2px rgb(125, 52, 128);
              cursor: pointer; 
              border-radius: 10px;  
              margin-right: 20px;
             }
.course{
             
      background: none;
      width: 20%;  
             
      font-size: 18px;  
      font-weight: bolder;
      padding: 10px; 
              /* padding-right: 10px;   */
      margin: 10px 0px;   
      border: solid 2px rgb(171, 106, 180);
      cursor: pointer; 
      border-radius: 10px;  
      margin-right: 20px;
      margin-top: 30%;
             }
 .trainer{
             
             background: none;
             width: 20%;  
             
              font-size: 18px;  
              font-weight: bolder;
              padding: 10px; 
              
              margin: 10px 0px;   
              border: solid 2px rgb(155, 96, 155);
              cursor: pointer; 
              border-radius: 10px;  
              margin-right: 20px;
             }
.events{
             
               
             width: 20%;  
             
              font-size: 18px;  
              font-weight: bolder;
              padding: 10px; 
             
              margin: 10px 0px;   
              border: solid 2px rgb(217, 154, 219);
              cursor: pointer; 
              border-radius: 10px;  
              margin-right: 30px;
             }
             button:hover {   
              opacity: 0.7; 
              background: white;  
              border: solid 1px rgb(71, 158, 173);
              color: rgb(20, 160, 153);}	
	</style>

  <h1>Welcome to school System</h1>


    <!-- <h1>{{students}}:students</h1>
  <h1>{{trainers}}:trainers</h1>
  <h1>{{courses}}:courses</h1> -->


  <!-- <div class="logo">
    <img src="https://www.segalfamilyfoundation.org/wp-content/uploads/2016/06/AkiraChix-Logo-2.png">
   </div> -->
	<div class="sidenav">
  

		<a href="/">Home</a>
		<a href="{%url 'student_list'%}">student</a>
		<a href="{%url 'trainer_list'%}">Trainer</a>
      <a href="{%url 'course_list' %}">Course</a>
		<a href="{%url 'cal:calendar'%}"class="menu-btn">Event</a>


	</div>




	<section class="home" id="home">
        
        <div class="max-width">
            <div class="home-content"> 
             
               <h2 class="text-2">AkiraChix School System</h2> 
                    <button class="student">{{student}} Students</button>
                    <button class="trainer">{{trainer}} Trainers</button>    
                    <button class="course">{{course}} Courses</button>
                    <button class="events">{{events}} Events</button>
                    </div>      
            </div>
            <div class="left">

            </div>
        </div>

       
    </section> 


	
</body>
</html>